//! `ServerHandler` implementation backing the MCP server.
//!
//! [`Handler`] is instantiated per session by the streamable-HTTP transport
//! (see [`crate::mcp::server::router`]) and wires the routing macros from
//! [`rmcp`] to the application-level [`crate::mcp::tools`] module.

use rmcp::{
    ErrorData as McpError, ServerHandler,
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::{CallToolResult, Implementation, ProtocolVersion, ServerCapabilities, ServerInfo},
    tool, tool_handler, tool_router,
};

use crate::app::AppState;
use crate::mcp::tools;

/// Per-session MCP server handler.
///
/// Holds a clone of the shared [`AppState`] and a [`ToolRouter`] generated by
/// `#[tool_router]`. The router field is read by macro-generated code only,
/// hence the `#[allow(dead_code)]` annotation.
#[derive(Clone)]
pub struct Handler {
    state: AppState,
    #[allow(dead_code)]
    tool_router: ToolRouter<Self>,
}

#[tool_router]
impl Handler {
    /// Creates a fresh handler backed by the supplied application state.
    pub fn new(state: AppState) -> Self {
        Self {
            state,
            tool_router: Self::tool_router(),
        }
    }

    /// Looks up a Fastly account domain by FQDN. Behavior lives in
    /// [`tools::find_domain::run`].
    #[tool(description = "Find a domain in the Fastly account by FQDN.")]
    async fn find_domain(
        &self,
        Parameters(args): Parameters<tools::find_domain::FindDomainArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::find_domain::run(&self.state, args).await
    }

    /// Looks up the Compute ACL entry covering a given IP. Behavior lives
    /// in [`tools::find_resource_acl_entry::run`].
    #[tool(
        description = "Find the Compute ACL entry (CIDR + action) that matches an IP, by `acl_id` and `ip` (single API call, no scan)."
    )]
    async fn find_resource_acl_entry(
        &self,
        Parameters(args): Parameters<tools::find_resource_acl_entry::FindResourceAclEntryArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::find_resource_acl_entry::run(&self.state, args).await
    }

    /// Lists the Fastly account's Compute ACLs (catalog only — entries
    /// are not enumerated). Behavior lives in
    /// [`tools::list_resource_acls::run`].
    #[tool(
        description = "List the Fastly account's Compute ACLs (catalog only — entries are not enumerated; use `find_resource_acl_entry` for IP lookup)."
    )]
    async fn list_resource_acls(
        &self,
        Parameters(args): Parameters<tools::list_resource_acls::ListResourceAclsArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::list_resource_acls::run(&self.state, args).await
    }

    /// Lists the Fastly account's config stores with item counts. Behavior
    /// lives in [`tools::list_resource_config_stores::run`].
    #[tool(description = "List the Fastly account's config stores with their item count.")]
    async fn list_resource_config_stores(
        &self,
        Parameters(args): Parameters<
            tools::list_resource_config_stores::ListResourceConfigStoresArgs,
        >,
    ) -> Result<CallToolResult, McpError> {
        tools::list_resource_config_stores::run(&self.state, args).await
    }

    /// Lists the keys of a single Fastly config store (values are not
    /// returned — read them one at a time with
    /// `get_resource_config_store_item_value`). Behavior lives in
    /// [`tools::list_resource_config_store_items::run`].
    #[tool(
        description = "List the keys of a Fastly config store, by `config_store_id` (values not returned)."
    )]
    async fn list_resource_config_store_items(
        &self,
        Parameters(args): Parameters<
            tools::list_resource_config_store_items::ListResourceConfigStoreItemsArgs,
        >,
    ) -> Result<CallToolResult, McpError> {
        tools::list_resource_config_store_items::run(&self.state, args).await
    }

    /// Fetches the value of a single key in a Fastly config store.
    /// Behavior lives in [`tools::get_resource_config_store_item_value::run`].
    #[tool(
        description = "Get the value of a single key in a Fastly config store, by `config_store_id` and `key`."
    )]
    async fn get_resource_config_store_item_value(
        &self,
        Parameters(args): Parameters<
            tools::get_resource_config_store_item_value::GetResourceConfigStoreItemValueArgs,
        >,
    ) -> Result<CallToolResult, McpError> {
        tools::get_resource_config_store_item_value::run(&self.state, args).await
    }

    /// Lists the Fastly account's KV stores. Behavior lives in
    /// [`tools::list_resource_kv_stores::run`].
    #[tool(description = "List the Fastly account's KV stores (cursor-paginated).")]
    async fn list_resource_kv_stores(
        &self,
        Parameters(args): Parameters<tools::list_resource_kv_stores::ListResourceKvStoresArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::list_resource_kv_stores::run(&self.state, args).await
    }

    /// Lists the keys of a single Fastly KV store (values are not
    /// returned — Fastly KV requires per-key reads). Behavior lives in
    /// [`tools::list_resource_kv_store_items::run`].
    #[tool(
        description = "List the keys of a Fastly KV store, by `store_id` (cursor-paginated, values not returned)."
    )]
    async fn list_resource_kv_store_items(
        &self,
        Parameters(args): Parameters<
            tools::list_resource_kv_store_items::ListResourceKvStoreItemsArgs,
        >,
    ) -> Result<CallToolResult, McpError> {
        tools::list_resource_kv_store_items::run(&self.state, args).await
    }

    /// Fetches the value of a single key in a Fastly KV store. Behavior
    /// lives in [`tools::get_resource_kv_store_item_value::run`].
    #[tool(
        description = "Get the value of a single key in a Fastly KV store, by `store_id` and `key`."
    )]
    async fn get_resource_kv_store_item_value(
        &self,
        Parameters(args): Parameters<
            tools::get_resource_kv_store_item_value::GetResourceKvStoreItemValueArgs,
        >,
    ) -> Result<CallToolResult, McpError> {
        tools::get_resource_kv_store_item_value::run(&self.state, args).await
    }

    /// Lists the Fastly account's secret stores. Behavior lives in
    /// [`tools::list_resource_secret_stores::run`].
    #[tool(description = "List the Fastly account's secret stores (cursor-paginated).")]
    async fn list_resource_secret_stores(
        &self,
        Parameters(args): Parameters<
            tools::list_resource_secret_stores::ListResourceSecretStoresArgs,
        >,
    ) -> Result<CallToolResult, McpError> {
        tools::list_resource_secret_stores::run(&self.state, args).await
    }

    /// Lists the secrets in a single Fastly secret store (names + opaque
    /// digests only — values are never exposed by the Fastly API).
    /// Behavior lives in [`tools::list_resource_secret_store_items::run`].
    #[tool(
        description = "List the secrets of a Fastly secret store, by `store_id` (cursor-paginated, names + digests only — values are never returned by Fastly)."
    )]
    async fn list_resource_secret_store_items(
        &self,
        Parameters(args): Parameters<
            tools::list_resource_secret_store_items::ListResourceSecretStoreItemsArgs,
        >,
    ) -> Result<CallToolResult, McpError> {
        tools::list_resource_secret_store_items::run(&self.state, args).await
    }

    /// Fetches a Fastly service by id. Behavior lives in
    /// [`tools::get_service::run`].
    #[tool(description = "Get a Fastly service's metadata and active version number.")]
    async fn get_service(
        &self,
        Parameters(args): Parameters<tools::get_service::GetServiceArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::get_service::run(&self.state, args).await
    }

    /// Fetches the Compute (wasm) package metadata for a service version.
    /// Behavior lives in [`tools::get_service_package::run`].
    #[tool(description = "Get a Fastly Compute (wasm) service version's package metadata.")]
    async fn get_service_package(
        &self,
        Parameters(args): Parameters<tools::get_service_package::GetServicePackageArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::get_service_package::run(&self.state, args).await
    }

    /// Lists the backends of a specific Fastly service version. Behavior
    /// lives in [`tools::list_service_backends::run`].
    #[tool(description = "List a Fastly service version's origin backends.")]
    async fn list_service_backends(
        &self,
        Parameters(args): Parameters<tools::list_service_backends::ListServiceBackendsArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_backends::run(&self.state, args).await
    }

    /// Lists the healthchecks of a specific Fastly service version. Behavior
    /// lives in [`tools::list_service_healthchecks::run`].
    #[tool(description = "List a Fastly service version's healthcheck probes.")]
    async fn list_service_healthchecks(
        &self,
        Parameters(args): Parameters<tools::list_service_healthchecks::ListServiceHealthchecksArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_healthchecks::run(&self.state, args).await
    }

    /// Lists the account-scoped resources (KV / secret / config stores)
    /// linked to a specific Fastly service version. Behavior lives in
    /// [`tools::list_service_resources::run`].
    #[tool(
        description = "List a Fastly service version's linked resources (KV / secret / config stores) — bridge to the account-scoped `list_resource_*` tools."
    )]
    async fn list_service_resources(
        &self,
        Parameters(args): Parameters<tools::list_service_resources::ListServiceResourcesArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_resources::run(&self.state, args).await
    }

    /// Lists the domains of a specific Fastly service version. Behavior
    /// lives in [`tools::list_service_domains::run`].
    #[tool(description = "List a Fastly service version's domains.")]
    async fn list_service_domains(
        &self,
        Parameters(args): Parameters<tools::list_service_domains::ListServiceDomainsArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_domains::run(&self.state, args).await
    }

    /// Lists the directors of a specific Fastly service version. Behavior
    /// lives in [`tools::list_service_directors::run`].
    #[tool(
        description = "List a Fastly service version's directors (load-balancing groups of backends)."
    )]
    async fn list_service_directors(
        &self,
        Parameters(args): Parameters<tools::list_service_directors::ListServiceDirectorsArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_directors::run(&self.state, args).await
    }

    /// Lists the edge dictionaries of a specific Fastly service version
    /// with their item count, digest, and last-updated timestamp. Behavior
    /// lives in [`tools::list_service_dictionaries::run`].
    #[tool(
        description = "List a Fastly service version's edge dictionaries with their item count, digest, and last-updated timestamp."
    )]
    async fn list_service_dictionaries(
        &self,
        Parameters(args): Parameters<tools::list_service_dictionaries::ListServiceDictionariesArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_dictionaries::run(&self.state, args).await
    }

    /// Lists the key/value items of a single edge dictionary. Behavior
    /// lives in [`tools::list_service_dictionary_items::run`].
    #[tool(
        description = "List the key/value items of a Fastly edge dictionary, by `service_id` and `dictionary_id`."
    )]
    async fn list_service_dictionary_items(
        &self,
        Parameters(args): Parameters<
            tools::list_service_dictionary_items::ListServiceDictionaryItemsArgs,
        >,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_dictionary_items::run(&self.state, args).await
    }

    /// Lists a Fastly service's open draft versions sitting above the
    /// currently-active one. Behavior lives in
    /// [`tools::list_service_versions::run`].
    #[tool(description = "List a Fastly service's active version and any drafts above it.")]
    async fn list_service_versions(
        &self,
        Parameters(args): Parameters<tools::list_service_versions::ListServiceVersionsArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_versions::run(&self.state, args).await
    }

    /// Lists the apex redirects of a specific Fastly VCL service version.
    /// Behavior lives in [`tools::list_service_vcl_apex_redirects::run`].
    #[tool(description = "List a Fastly VCL service version's apex redirects.")]
    async fn list_service_vcl_apex_redirects(
        &self,
        Parameters(args): Parameters<
            tools::list_service_vcl_apex_redirects::ListServiceVclApexRedirectsArgs,
        >,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_vcl_apex_redirects::run(&self.state, args).await
    }

    /// Lists the cache-settings rules of a specific Fastly VCL service
    /// version. Behavior lives in
    /// [`tools::list_service_vcl_cache_settings::run`].
    #[tool(description = "List a Fastly VCL service version's cache-settings rules.")]
    async fn list_service_vcl_cache_settings(
        &self,
        Parameters(args): Parameters<
            tools::list_service_vcl_cache_settings::ListServiceVclCacheSettingsArgs,
        >,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_vcl_cache_settings::run(&self.state, args).await
    }

    /// Lists the conditions of a specific Fastly VCL service version.
    /// Behavior lives in [`tools::list_service_vcl_conditions::run`].
    #[tool(
        description = "List a Fastly VCL service version's conditions (named VCL boolean expressions)."
    )]
    async fn list_service_vcl_conditions(
        &self,
        Parameters(args): Parameters<
            tools::list_service_vcl_conditions::ListServiceVclConditionsArgs,
        >,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_vcl_conditions::run(&self.state, args).await
    }

    /// Lists the gzip configurations of a specific Fastly VCL service
    /// version. Behavior lives in [`tools::list_service_vcl_gzip::run`].
    #[tool(description = "List a Fastly VCL service version's gzip compression configurations.")]
    async fn list_service_vcl_gzip(
        &self,
        Parameters(args): Parameters<tools::list_service_vcl_gzip::ListServiceVclGzipArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_vcl_gzip::run(&self.state, args).await
    }

    /// Lists the header rules of a specific Fastly VCL service version.
    /// Behavior lives in [`tools::list_service_vcl_headers::run`].
    #[tool(
        description = "List a Fastly VCL service version's header rules (set/append/delete/regex)."
    )]
    async fn list_service_vcl_headers(
        &self,
        Parameters(args): Parameters<tools::list_service_vcl_headers::ListServiceVclHeadersArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_vcl_headers::run(&self.state, args).await
    }

    /// Lists the rate limiters of a specific Fastly VCL service version.
    /// Behavior lives in [`tools::list_service_vcl_rate_limiters::run`].
    #[tool(description = "List a Fastly VCL service version's rate limiters.")]
    async fn list_service_vcl_rate_limiters(
        &self,
        Parameters(args): Parameters<
            tools::list_service_vcl_rate_limiters::ListServiceVclRateLimitersArgs,
        >,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_vcl_rate_limiters::run(&self.state, args).await
    }

    /// Lists the request-settings rules of a specific Fastly VCL service
    /// version. Behavior lives in
    /// [`tools::list_service_vcl_request_settings::run`].
    #[tool(description = "List a Fastly VCL service version's request-settings rules.")]
    async fn list_service_vcl_request_settings(
        &self,
        Parameters(args): Parameters<
            tools::list_service_vcl_request_settings::ListServiceVclRequestSettingsArgs,
        >,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_vcl_request_settings::run(&self.state, args).await
    }

    /// Lists the response objects of a specific Fastly VCL service version.
    /// Behavior lives in [`tools::list_service_vcl_response_objects::run`].
    #[tool(
        description = "List a Fastly VCL service version's response objects (canned HTTP responses)."
    )]
    async fn list_service_vcl_response_objects(
        &self,
        Parameters(args): Parameters<
            tools::list_service_vcl_response_objects::ListServiceVclResponseObjectsArgs,
        >,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_vcl_response_objects::run(&self.state, args).await
    }

    /// Lists the VCL snippets of a specific Fastly VCL service version.
    /// Behavior lives in [`tools::list_service_vcl_snippets::run`].
    #[tool(
        description = "List a Fastly VCL service version's VCL snippets (code injected into a specific request-lifecycle phase)."
    )]
    async fn list_service_vcl_snippets(
        &self,
        Parameters(args): Parameters<tools::list_service_vcl_snippets::ListServiceVclSnippetsArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_vcl_snippets::run(&self.state, args).await
    }
}

#[tool_handler]
impl ServerHandler for Handler {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::from_build_env())
            .with_protocol_version(ProtocolVersion::V_2025_11_25)
            .with_instructions(INSTRUCTIONS.to_string())
    }
}

/// Server-level guidance returned in `initialize.serverInfo.instructions`.
///
/// This is loaded once into the agent's context (unlike per-tool descriptions
/// which the agent re-reads when picking a tool), so it is the right place
/// for cross-cutting hints: scope, freshness model, typical workflow, and
/// boundary behavior shared by every tool.
const INSTRUCTIONS: &str = "\
Read-only inspection of a Fastly account.

Services have multiple versions; exactly one is active at a time and active versions are immutable. \
Version-scoped tools (`list_service_*`) take `(service_id, version)` and return deterministic snapshots — \
two calls with identical arguments yield identical results. Account-scoped tools (`list_resource_*`, `find_resource_*`) take no `service_id` / `version`.

Entry points (no version):
- `find_domain` — FQDN → service_id (Domain Management v1; `fqdn_match` controls match strategy, default permissive).
- `get_service` — metadata, active `version`, and a `dependencies` count map for triage.
- `list_service_versions` — active version + open drafts above it (locked history filtered out).

Account-scoped resources:
- Config stores: `list_resource_config_stores` → `list_resource_config_store_items` (keys) → `get_resource_config_store_item_value`.
- KV stores (cursor-paginated): `list_resource_kv_stores` → `list_resource_kv_store_items` (keys, optional `prefix` filter) → `get_resource_kv_store_item_value`.
- Secret stores: `list_resource_secret_stores` → `list_resource_secret_store_items` (name + opaque digest only). Fastly never returns secret values — there is intentionally no per-value tool.
- Compute ACLs: `list_resource_acls` → `find_resource_acl_entry` (single-call IP lookup, no scan). Entries are intentionally not enumerated.

Multi-kind service tools (any service type):
- `list_service_backends`, `list_service_directors`, `list_service_domains`, `list_service_healthchecks`
- `list_service_dictionaries` → `list_service_dictionary_items` (the items endpoint is not version-scoped; write-only dicts return a clean text signal instead of 403)
- `list_service_resources` — links to account-scoped stores (KV / secret / config) attached to this version

Compute-only (`type == \"wasm\"`):
- `get_service_package` — package metadata (name, language, size, files_hash)

VCL-only (`type == \"vcl\"`):
- `list_service_vcl_apex_redirects`, `list_service_vcl_cache_settings`, `list_service_vcl_conditions`, `list_service_vcl_gzip`, `list_service_vcl_headers`, `list_service_vcl_rate_limiters`, `list_service_vcl_request_settings`, `list_service_vcl_response_objects`, `list_service_vcl_snippets`

Cross-references:
- `list_service_backends[].healthcheck` and `list_service_directors[].backends[]` reference healthchecks/backends by `name`.
- VCL conditions are referenced by `name` from cache_settings, headers, request/response_settings, and rate_limiters via `*_condition` fields.
- `list_service_resources[].resource_id` + `.resource_type` (`config` | `kv-store` | `secret-store`) drive the next call to the matching account-scoped `*_items` tool.
- 404s from Fastly (unknown service / version / store / key / ACL) are downgraded to plain-text messages — treat as a clean empty signal, not a failure to retry.\
";
