//! `ServerHandler` implementation backing the MCP server.
//!
//! [`Handler`] is instantiated per session by the streamable-HTTP transport
//! (see [`crate::mcp::server::router`]) and wires the routing macros from
//! [`rmcp`] to the application-level [`crate::mcp::tools`] and
//! [`crate::mcp::tasks`] modules.

use std::sync::Arc;

use rmcp::{
    ErrorData as McpError, ServerHandler,
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::*,
    task_handler,
    task_manager::OperationProcessor,
    tool, tool_handler, tool_router,
};
use tokio::sync::Mutex;

use crate::app::AppState;
use crate::mcp::{tasks, tools};

/// Per-session MCP server handler.
///
/// Holds a clone of the shared [`AppState`], a [`ToolRouter`] generated by
/// `#[tool_router]`, and a [`OperationProcessor`] used by the
/// `#[task_handler]` macro to dispatch task-augmented `tools/call` requests
/// (`tasks/get`, `tasks/result`, `tasks/list`, `tasks/cancel`).
///
/// Both `tool_router` and `processor` are read by macro-generated code only,
/// hence the `#[allow(dead_code)]` annotations.
#[derive(Clone)]
pub struct Handler {
    state: AppState,
    #[allow(dead_code)]
    tool_router: ToolRouter<Self>,
    #[allow(dead_code)]
    processor: Arc<Mutex<OperationProcessor>>,
}

#[tool_router]
impl Handler {
    /// Creates a fresh handler backed by the supplied application state.
    pub fn new(state: AppState) -> Self {
        Self {
            state,
            tool_router: Self::tool_router(),
            processor: Arc::new(Mutex::new(OperationProcessor::new())),
        }
    }

    /// Greets the caller. The behavior lives in [`tools::hello::run`];
    /// this method only adapts the rmcp parameter wrapper and delegates.
    #[tool(description = "Greet someone (or the world if no name is given).")]
    async fn hello(
        &self,
        Parameters(args): Parameters<tools::hello::HelloArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::hello::run(&self.state, args).await
    }

    /// Looks up a Fastly domain by FQDN. Behavior lives in
    /// [`tools::find_domain::run`].
    #[tool(
        description = "Find a domain in the Fastly account by FQDN."
    )]
    async fn find_domain(
        &self,
        Parameters(args): Parameters<tools::find_domain::FindDomainArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::find_domain::run(&self.state, args).await
    }

    /// Fetches a Fastly service by id. Behavior lives in
    /// [`tools::get_service::run`].
    #[tool(
        description = "Get a Fastly service by its service_id."
    )]
    async fn get_service(
        &self,
        Parameters(args): Parameters<tools::get_service::GetServiceArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::get_service::run(&self.state, args).await
    }

    /// Long-running demo tool that sleeps 15 seconds (overridable). Designed
    /// to validate the task-augmented invocation path end-to-end.
    ///
    /// Declared with `task_support = "required"`, which forces clients to
    /// invoke this tool with the `task` field on `tools/call`. A plain
    /// synchronous call is rejected by the server with `-32601`.
    #[tool(
        description = "Sleeps for `seconds` seconds (default 15). Must be invoked as a task.",
        execution(task_support = "required")
    )]
    async fn slow_demo(
        &self,
        Parameters(args): Parameters<tasks::slow_demo::SlowDemoArgs>,
    ) -> Result<CallToolResult, McpError> {
        tasks::slow_demo::run(&self.state, args).await
    }
}

#[tool_handler]
#[task_handler]
impl ServerHandler for Handler {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(
            ServerCapabilities::builder()
                .enable_tools()
                .enable_tasks_with(TasksCapability::server_default())
                .build(),
        )
        .with_server_info(Implementation::from_build_env())
        .with_protocol_version(ProtocolVersion::V_2025_11_25)
        .with_instructions("Claude Rust Specialist — Rust workspace assistant.".to_string())
    }
}
