//! `ServerHandler` implementation backing the MCP server.
//!
//! [`Handler`] is instantiated per session by the streamable-HTTP transport
//! (see [`crate::mcp::server::router`]) and wires the routing macros from
//! [`rmcp`] to the application-level [`crate::mcp::tools`] module.

use rmcp::{
    ErrorData as McpError, ServerHandler,
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::*,
    tool, tool_handler, tool_router,
};


use crate::app::AppState;
use crate::mcp::tools;

/// Per-session MCP server handler.
///
/// Holds a clone of the shared [`AppState`] and a [`ToolRouter`] generated by
/// `#[tool_router]`. The router field is read by macro-generated code only,
/// hence the `#[allow(dead_code)]` annotation.
#[derive(Clone)]
pub struct Handler {
    state: AppState,
    #[allow(dead_code)]
    tool_router: ToolRouter<Self>,
}

#[tool_router]
impl Handler {
    /// Creates a fresh handler backed by the supplied application state.
    pub fn new(state: AppState) -> Self {
        Self {
            state,
            tool_router: Self::tool_router(),
        }
    }

    /// Looks up a Fastly account domain by FQDN. Behavior lives in
    /// [`tools::find_domain::run`].
    #[tool(description = "Find a domain in the Fastly account by FQDN.")]
    async fn find_domain(
        &self,
        Parameters(args): Parameters<tools::find_domain::FindDomainArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::find_domain::run(&self.state, args).await
    }

    /// Fetches a Fastly service by id. Behavior lives in
    /// [`tools::get_service::run`].
    #[tool(
        description = "Get a Fastly service's metadata and active version number."
    )]
    async fn get_service(
        &self,
        Parameters(args): Parameters<tools::get_service::GetServiceArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::get_service::run(&self.state, args).await
    }

    /// Fetches the Compute (wasm) package metadata for a service version.
    /// Behavior lives in [`tools::get_service_package::run`].
    #[tool(description = "Get a Fastly Compute (wasm) service version's package metadata.")]
    async fn get_service_package(
        &self,
        Parameters(args): Parameters<tools::get_service_package::GetServicePackageArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::get_service_package::run(&self.state, args).await
    }

    /// Lists the backends of a specific Fastly service version. Behavior
    /// lives in [`tools::list_service_backends::run`].
    #[tool(description = "List a Fastly service version's origin backends.")]
    async fn list_service_backends(
        &self,
        Parameters(args): Parameters<tools::list_service_backends::ListServiceBackendsArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_backends::run(&self.state, args).await
    }

    /// Lists the healthchecks of a specific Fastly service version. Behavior
    /// lives in [`tools::list_service_healthchecks::run`].
    #[tool(description = "List a Fastly service version's healthcheck probes.")]
    async fn list_service_healthchecks(
        &self,
        Parameters(args): Parameters<tools::list_service_healthchecks::ListServiceHealthchecksArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_healthchecks::run(&self.state, args).await
    }

    /// Lists the domains of a specific Fastly service version. Behavior
    /// lives in [`tools::list_service_domains::run`].
    #[tool(description = "List a Fastly service version's domains.")]
    async fn list_service_domains(
        &self,
        Parameters(args): Parameters<tools::list_service_domains::ListServiceDomainsArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_domains::run(&self.state, args).await
    }

    /// Lists the directors of a specific Fastly service version. Behavior
    /// lives in [`tools::list_service_directors::run`].
    #[tool(description = "List a Fastly service version's directors (load-balancing groups of backends).")]
    async fn list_service_directors(
        &self,
        Parameters(args): Parameters<tools::list_service_directors::ListServiceDirectorsArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_directors::run(&self.state, args).await
    }

    /// Lists the edge dictionaries of a specific Fastly service version
    /// together with their key/value items. Behavior lives in
    /// [`tools::list_service_dictionaries::run`].
    #[tool(description = "List a Fastly service version's edge dictionaries with their key/value items.")]
    async fn list_service_dictionaries(
        &self,
        Parameters(args): Parameters<
            tools::list_service_dictionaries::ListServiceDictionariesArgs,
        >,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_dictionaries::run(&self.state, args).await
    }

    /// Lists a Fastly service's open draft versions sitting above the
    /// currently-active one. Behavior lives in
    /// [`tools::list_service_versions::run`].
    #[tool(description = "List a Fastly service's active version and any drafts above it.")]
    async fn list_service_versions(
        &self,
        Parameters(args): Parameters<tools::list_service_versions::ListServiceVersionsArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_versions::run(&self.state, args).await
    }

    /// Lists the apex redirects of a specific Fastly VCL service version.
    /// Behavior lives in [`tools::list_service_vcl_apex_redirects::run`].
    #[tool(description = "List a Fastly VCL service version's apex redirects.")]
    async fn list_service_vcl_apex_redirects(
        &self,
        Parameters(args): Parameters<
            tools::list_service_vcl_apex_redirects::ListServiceVclApexRedirectsArgs,
        >,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_vcl_apex_redirects::run(&self.state, args).await
    }

    /// Lists the cache-settings rules of a specific Fastly VCL service
    /// version. Behavior lives in
    /// [`tools::list_service_vcl_cache_settings::run`].
    #[tool(description = "List a Fastly VCL service version's cache-settings rules.")]
    async fn list_service_vcl_cache_settings(
        &self,
        Parameters(args): Parameters<
            tools::list_service_vcl_cache_settings::ListServiceVclCacheSettingsArgs,
        >,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_vcl_cache_settings::run(&self.state, args).await
    }

    /// Lists the conditions of a specific Fastly VCL service version.
    /// Behavior lives in [`tools::list_service_vcl_conditions::run`].
    #[tool(description = "List a Fastly VCL service version's conditions (named VCL boolean expressions).")]
    async fn list_service_vcl_conditions(
        &self,
        Parameters(args): Parameters<
            tools::list_service_vcl_conditions::ListServiceVclConditionsArgs,
        >,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_vcl_conditions::run(&self.state, args).await
    }

    /// Lists the gzip configurations of a specific Fastly VCL service
    /// version. Behavior lives in [`tools::list_service_vcl_gzip::run`].
    #[tool(description = "List a Fastly VCL service version's gzip compression configurations.")]
    async fn list_service_vcl_gzip(
        &self,
        Parameters(args): Parameters<tools::list_service_vcl_gzip::ListServiceVclGzipArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_vcl_gzip::run(&self.state, args).await
    }

    /// Lists the header rules of a specific Fastly VCL service version.
    /// Behavior lives in [`tools::list_service_vcl_headers::run`].
    #[tool(description = "List a Fastly VCL service version's header rules (set/append/delete/regex).")]
    async fn list_service_vcl_headers(
        &self,
        Parameters(args): Parameters<tools::list_service_vcl_headers::ListServiceVclHeadersArgs>,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_vcl_headers::run(&self.state, args).await
    }

    /// Lists the rate limiters of a specific Fastly VCL service version.
    /// Behavior lives in [`tools::list_service_vcl_rate_limiters::run`].
    #[tool(description = "List a Fastly VCL service version's rate limiters.")]
    async fn list_service_vcl_rate_limiters(
        &self,
        Parameters(args): Parameters<
            tools::list_service_vcl_rate_limiters::ListServiceVclRateLimitersArgs,
        >,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_vcl_rate_limiters::run(&self.state, args).await
    }

    /// Lists the request-settings rules of a specific Fastly VCL service
    /// version. Behavior lives in
    /// [`tools::list_service_vcl_request_settings::run`].
    #[tool(description = "List a Fastly VCL service version's request-settings rules.")]
    async fn list_service_vcl_request_settings(
        &self,
        Parameters(args): Parameters<
            tools::list_service_vcl_request_settings::ListServiceVclRequestSettingsArgs,
        >,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_vcl_request_settings::run(&self.state, args).await
    }

    /// Lists the response objects of a specific Fastly VCL service version.
    /// Behavior lives in [`tools::list_service_vcl_response_objects::run`].
    #[tool(description = "List a Fastly VCL service version's response objects (canned HTTP responses).")]
    async fn list_service_vcl_response_objects(
        &self,
        Parameters(args): Parameters<
            tools::list_service_vcl_response_objects::ListServiceVclResponseObjectsArgs,
        >,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_vcl_response_objects::run(&self.state, args).await
    }

    /// Lists the VCL snippets of a specific Fastly VCL service version.
    /// Behavior lives in [`tools::list_service_vcl_snippets::run`].
    #[tool(description = "List a Fastly VCL service version's VCL snippets (code injected into a specific request-lifecycle phase).")]
    async fn list_service_vcl_snippets(
        &self,
        Parameters(args): Parameters<
            tools::list_service_vcl_snippets::ListServiceVclSnippetsArgs,
        >,
    ) -> Result<CallToolResult, McpError> {
        tools::list_service_vcl_snippets::run(&self.state, args).await
    }
}

#[tool_handler]
impl ServerHandler for Handler {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(
            ServerCapabilities::builder()
                .enable_tools()
                .build(),
        )
        .with_server_info(Implementation::from_build_env())
        .with_protocol_version(ProtocolVersion::V_2025_11_25)
        .with_instructions(INSTRUCTIONS.to_string())
    }
}

/// Server-level guidance returned in `initialize.serverInfo.instructions`.
///
/// This is loaded once into the agent's context (unlike per-tool descriptions
/// which the agent re-reads when picking a tool), so it is the right place
/// for cross-cutting hints: scope, freshness model, typical workflow, and
/// boundary behavior shared by every tool.
const INSTRUCTIONS: &str = "\
Read-only inspection of a Fastly account's service configuration.

Each Fastly service has multiple versions; exactly one is active at any time, and active versions are immutable. \
The `list_service_*` tools all take `(service_id, version)` and return a deterministic snapshot — \
two calls with identical arguments yield identical results.

Entry points (no `version` argument):

`find_domain` looks up a domain in the account's Domain Management v1 catalog by FQDN.
Returns the domain id, FQDN, associated `service_id` (when bound), and TLS activation/verification flags.
Use it when you only know a hostname and need to discover which service serves it.
The optional `fqdn_match` parameter controls how Fastly compares the input —
accepted values: `\"exact\"`, `\"contains\"`, `\"begins_with\"`, `\"ends_with\"`.
Without it, Fastly applies a permissive default that may also return sub-domains
(e.g. a query for `example.com` may also surface `sub.example.com`).

`get_service` fetches a service's metadata by `service_id`.
Returns the service name, type (`vcl` or `wasm`), the currently-active `version` number, timestamps,
and a `dependencies` map counting every config object attached to the active version
(backends, directors, domains, healthchecks, plus the VCL-only object types when applicable).
Use it as the standard entry point once a `service_id` is in hand —
the active version it returns is what you'll feed to the version-scoped tools below.

`list_service_versions` enumerates a service's active version plus any open draft versions sitting above it.
Locked historical versions and post-rollback artifacts are filtered out.
Use it to inspect in-flight work that hasn't been deployed yet —
typically when the agent needs to reason about pending changes or compare a draft against the live config.

Once a `(service_id, version)` pair is in hand, pass it to one of:

Multi-kind (works on every service):
- `list_service_backends` — origin backends
- `list_service_dictionaries` — edge dictionaries with their key/value items
- `list_service_directors` — load-balancing groups of backends
- `list_service_domains` — domains routed to this version
- `list_service_healthchecks` — health probes

Compute-only (require `type: \"wasm\"`):
- `get_service_package` — Compute package metadata (name, language, files_hash, …)

VCL-only (require `type: \"vcl\"`):
- `list_service_vcl_apex_redirects` — apex-domain redirects
- `list_service_vcl_cache_settings` — cache rules (TTL, action, gating)
- `list_service_vcl_conditions` — named VCL boolean expressions
- `list_service_vcl_gzip` — gzip compression configurations
- `list_service_vcl_headers` — header rules (set/append/delete/regex)
- `list_service_vcl_rate_limiters` — RPS-based rate limiters
- `list_service_vcl_request_settings` — request-shaping rules
- `list_service_vcl_response_objects` — canned HTTP responses
- `list_service_vcl_snippets` — VCL code snippets

Cross-references between tools:
- A backend's `healthcheck` field is the `name` of a `list_service_healthchecks` entry.
- A director's `backends` array contains the `name`s of `list_service_backends` entries.
- Cache settings, headers, request/response settings, and rate limiters reference VCL conditions \
  by `name` via their `*_condition` fields — chain with `list_service_vcl_conditions`.\
";
